openapi: 3.0.0
info:
  title: VisionBoard API
  description: API for VisionBoard - Transforming Data into Actionable insights
  version: 1.0.0

paths:
  /api/v1/__health:
    get:
      summary: Health check endpoint
      description: Returns the current health status of the API
      operationId: getHealthStatus
      tags:
        - System
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-05-03T07:20:16.000Z'
                required:
                  - status
                  - timestamp

  /api/v1/checks:
    get:
      summary: List all available checks
      description: Returns the all available checks
      operationId: getChecks
      tags:
        - System
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
                schema:
                  type: array
                  items:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: number
                        example: 9
                      title:
                        type: string
                        example: Check title
                      description:
                        type: string
                        example: Check description
                      default_section_number:
                        type: string
                        example: "1"
                      default_section_name:
                        type: string
                        example: Check section name
                      code_name:
                        type: string
                        example: check_code_name
                      default_priority_group:
                        type: string
                        example: R6
                      is_c_scrm:
                        type: boolean
                        example: true
                      implementation_status:
                        type: string
                        example: completed
                      implementation_type:
                        nullable: true
                        type: string
                        example: manual
                      implementation_details_reference:
                        type: string
                        nullable: true
                        example: https://example.com/implementation-details
                      details_url:
                        type: string
                        example: https://openpathfinder.com/docs/checks/annualDependencyRefresh
                      created_at:
                        type: string
                        format: date-time
                        example: '2025-05-03T07:20:16.000Z'
                      updated_at:
                        type: string
                        format: date-time
                        example: '2025-05-03T07:20:16.000Z'
  
  /api/v1/generate-reports:
    post:
      summary: Generate static reports
      description: Triggers the generation of static reports
      operationId: generateReports
      tags:
        - Reports
      responses:
        '202':
          description: Report generation accepted
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                    enum: [completed, failed]
                    example: completed
                  startedAt:
                    type: string
                    format: date-time
                    example: '2025-05-03T07:20:16.000Z'
                  finishedAt:
                    type: string
                    format: date-time
                    example: '2025-05-03T07:20:20.000Z'
                required:
                  - status
                  - startedAt
                  - finishedAt
        '500':
          description: Report generation failed
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                    enum: [failed]
                    example: failed
                  startedAt:
                    type: string
                    format: date-time
                    example: '2025-05-03T07:20:16.000Z'
                  finishedAt:
                    type: string
                    format: date-time
                    example: '2025-05-03T07:20:20.000Z'
                required:
                  - status
                  - startedAt
                  - finishedAt

components:
  schemas: {}