const list = [
  {
    title: 'Training on secure software design',
    description: 'At least one primary maintainer has taken the training on Secure Software Design',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'softwareDesignTraining',
    priority_group: 'P0',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://attack.mitre.org/mitigations/M1013/',
    mitre_description: 'M1013',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#0.know_secure_design',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [know_secure_design]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/softwareDesignTraining'
  },
  {
    title: 'Training on OWASP Top 10 or equivalent',
    description: 'At least one primary maintainer has taken the training on OWASP Top 10 or Equivalent',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'owaspTop10Training',
    priority_group: 'P0',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://attack.mitre.org/mitigations/M1013/',
    mitre_description: 'M1013',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#0.know_common_errors',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [know_common_errors]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/owaspTop10Training'
  },
  {
    title: 'Enforce MFA in GitHub organization(s)',
    description: 'Multi Factor authentication (MFA) enforced across the Github Organization(s)',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'githubOrgMFA',
    priority_group: 'P1',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    how_to_url: 'https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/enterprise/enterprise_enforce_two_factor_authentication.html',
    sources_description: 'OpenSSF SCM Best PracticesOpenSSF Best Practices Badge Gold Level [require_2FA]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/githubOrgMFA'
  },
  {
    title: 'Enforce MFA in npm organization(s)',
    description: 'Multi Factor Authentication (MFA) enforced across the npm organization(s)',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'npmOrgMFA',
    priority_group: 'P1',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    how_to_url: 'https://docs.npmjs.com/requiring-two-factor-authentication-in-your-organization',
    how_to_description: 'npm Docs',
    sources_url: 'https://github.com/ossf/package-manager-best-practices/blob/main/published/npm.md',
    sources_description: 'OpenSSF npm Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/npmOrgMFA'
  },
  {
    title: 'Enforce MFA in all the tools',
    description: 'Multi Factor Authentication (MFA) enforced in all tools wherever technically feasible',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'orgToolingMFA',
    priority_group: 'P1',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cloud-native-security-whitepaper.md',
    sources_description: 'CNCF CNSWP v1.0',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/orgToolingMFA'
  },
  {
    title: 'Use MFA against impersonation',
    description: 'Use Multi Factor Authentication (MFA) methods that defend against impersonation when available ',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'MFAImpersonationDefense',
    priority_group: 'P1',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/290.html',
    mitre_description: 'CWE-290',
    how_to_url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa',
    how_to_description: 'Github Docs',
    sources_url: 'https://www.bestpractices.dev/en/criteria/2#2.secure_2FA',
    sources_description: 'OpenSSF Best Practices Badge Gold Level [secure_2FA]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/MFAImpersonationDefense'
  },
  {
    title: 'Check sensitive information',
    description: 'No secrets or credentials are included in the source code',
    section_number: '3',
    section_name: 'service authentication',
    code_name: 'noSensitiveInfoInRepositories',
    priority_group: 'P2',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/540.html',
    mitre_description: 'CWE-540',
    how_to_url: 'https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning',
    how_to_description: 'Github Docs',
    sources_url: 'https://www.bestpractices.dev/en/criteria#0.no_leaked_credentials',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [no_leaked_credentials]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/noSensitiveInfoInRepositories'
  },
  {
    title: 'Ensure that the secrets are injected at runtime',
    description: 'Secrets are injected at runtime, such as environment variables or as a file (eg: use Github Secrets)',
    section_number: '3',
    section_name: 'service authentication',
    code_name: 'injectedSecretsAtRuntime',
    priority_group: 'P2',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/538.html',
    mitre_description: 'CWE-538',
    how_to_url: 'https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-an-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cloud-native-security-whitepaper.md#secrets-encryption',
    sources_description: 'CNCF CNSWP 2.0 #195',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/injectedSecretsAtRuntime'
  },
  {
    title: 'Ensure that all the commits are scanned',
    description: 'All commits are scanned for secrets and credentials ',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'scanCommitsForSensitiveInfo',
    priority_group: 'P2',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/540.html',
    mitre_description: 'CWE-540',
    how_to_url: 'https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#user-content-fnref-21-4e56305414bd02da4843ec1d7d856144',
    sources_description: 'CNCF SSCP v1.0 #184',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/scanCommitsForSensitiveInfo'
  },
  {
    title: 'Block new commits with secrets or credentials',
    description: 'New commits containing secrets or credentials are blocked from merging',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'preventLandingSensitiveCommits',
    priority_group: 'P2',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/358.html',
    mitre_description: 'CWE-358',
    how_to_url: 'https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning',
    how_to_description: 'Github Docs',
    sources_url: 'https://www.bestpractices.dev/en/criteria#0.no_leaked_credentials',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [no_leaked_credentials]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/preventLandingSensitiveCommits'
  },
  {
    title: 'Use SSH keys with passphrases for repository access',
    description: 'Use SSH keys for developer access to source code repositories and use a passphrase',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'SSHKeysRequired',
    priority_group: 'P3',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/309.html',
    mitre_description: 'CWE-309',
    how_to_url: 'https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#use-ssh-keys-to-provide-developers-access-to-source-code-repositories',
    sources_description: 'CNCF SSCP v1.0 #192',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/SSHKeysRequired'
  },
  {
    title: 'Publish to npm using MFA-Enabled accounts',
    description: 'Publish to npm using an MFA-enabled account rather than single factor legacy or granular access tokens',
    section_number: '3',
    section_name: 'service authentication',
    code_name: 'npmPublicationMFA',
    priority_group: 'P3',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    sources_url: 'https://docs.npmjs.com/creating-and-viewing-access-tokens',
    sources_description: 'npm Docs',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/npmPublicationMFA'
  },
  {
    title: 'Secure GitHub Webhooks with secrets',
    description: 'Ensure that Github Webhooks use secrets',
    section_number: '3',
    section_name: 'service authentication',
    code_name: 'githubWebhookSecrets',
    priority_group: 'P3',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/306',
    mitre_description: 'CWE-306',
    how_to_url: 'https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#webhooks',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/githubWebhookSecrets'
  },
  {
    title: 'Restrict default GitHub Org member permissions',
    description: 'Default GitHub organization member permissions should be restricted',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'restrictedOrgPermissions',
    priority_group: 'P4',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://capec.mitre.org/data/definitions/180.html',
    mitre_description: 'CAPEC-180',
    how_to_url: 'https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/setting-base-permissions-for-an-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/organization/default_repository_permission_is_not_none.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/restrictedOrgPermissions'
  },
  {
    title: 'Allow only admins to create public repositories',
    description: 'Only admins should be able to create public repositories',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'adminRepoCreationOnly',
    priority_group: 'P4',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://capec.mitre.org/data/definitions/122.html',
    mitre_description: 'CAPEC-122',
    how_to_url: 'https://docs.github.com/en/organizations/managing-organization-settings/restricting-repository-creation-in-your-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/organization/non_admins_can_create_public_repositories.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/adminRepoCreationOnly'
  },
  {
    title: 'Prevent admins from bypassing branch protection',
    description: 'Do not allow admins to bypass branch protection settings',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'preventBranchProtectionBypass',
    priority_group: 'P4',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://capec.mitre.org/data/definitions/122.html',
    mitre_description: 'CAPEC-122',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#do-not-allow-bypassing-the-above-settings',
    how_to_description: 'Github Docs',
    sources_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches',
    sources_description: 'Github Supply Chain Security Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/preventBranchProtectionBypass'
  },
  {
    title: 'Define roles aligned to functional responsibilities',
    description: 'Define roles aligned to functional responsibilities',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'defineFunctionalRoles',
    priority_group: 'P4',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://capec.mitre.org/data/definitions/122.html',
    mitre_description: 'CAPEC-122',
    how_to_url: 'https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#define-roles-aligned-to-functional-responsibilities',
    sources_description: 'CNCF SSCP v1.0 #188',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/defineFunctionalRoles'
  },
  {
    title: 'Define teams/individuals with write access to repositories',
    description: 'Define individuals/teams who write access to a GitHub Repository',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'githubWriteAccessRoles',
    priority_group: 'P4',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://capec.mitre.org/data/definitions/180.html',
    mitre_description: 'CAPEC-180',
    how_to_url: 'https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#define-individualsteams-that-are-responsible-for-code-in-a-repository-and-associated-coding-conventions',
    sources_description: 'CNCF SSCP v1.0 #185',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/githubWriteAccessRoles'
  },
  {
    title: 'Configure two or more owners for access continuity',
    description: 'Have at least two owners configured for access continuity',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'twoOrMoreOwnersForAccess',
    priority_group: 'P4',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://attack.mitre.org/mitigations/M1026/',
    mitre_description: 'M1026',
    how_to_url: 'https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#1.access_continuity',
    sources_description: 'OpenSSF Best Practices Badge Silver Level [access_continuity]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/twoOrMoreOwnersForAccess'
  },
  {
    title: 'Patch actively exploited critical vulnerabilities within 30 Days',
    description: 'Actively exploited critical vulnerabilities patched within 30 Days',
    section_number: '5',
    section_name: 'vulnerability management',
    code_name: 'patchCriticalVulns30Days',
    priority_group: 'P5',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria#0.vulnerabilities_critical_fixed',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [vulnerabilities_critical_fixed]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/patchCriticalVulns30Days'
  },
  {
    title: 'Patch non-critical vulnerabilities within 90 days',
    description: 'Ensure non-critical exploitable vulnerabilities are patched within 90 days',
    section_number: '5',
    section_name: 'vulnerability management',
    code_name: 'patchNonCriticalVulns90Days',
    priority_group: 'P5',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    sources_url: 'https://googleprojectzero.blogspot.com/p/vulnerability-disclosure-policy.html',
    sources_description: 'Google Project Zero Vulnerability Disclosure Policy',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/patchNonCriticalVulns90Days'
  },
  {
    title: 'Automate dependency vulnerability identification',
    description: 'Implement an automated process to identify dependencies with publicly disclosed vulnerabilities',
    section_number: '11',
    section_name: 'dependency management',
    code_name: 'automateVulnDetection',
    priority_group: 'P6',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1395.html',
    mitre_description: 'CWE-1395',
    how_to_url: 'https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories',
    how_to_description: 'Github Docs',
    sources_url: 'https://scvs.owasp.org/scvs/v5-component-analysis/',
    sources_description: 'OWASP SCVS L1 5.4',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/automateVulnDetection'
  },
  {
    title: 'Use automated static code analysis tools',
    description: 'Implement automated static code analysis tools (e.g., ESLint)',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'staticCodeAnalysis',
    priority_group: 'P6',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1076.html',
    mitre_description: 'CWE-1076',
    how_to_url: 'https://eslint.org/docs/latest/use/getting-started#installation-and-usage',
    how_to_description: 'ESLint Docs',
    sources_url: 'https://scvs.owasp.org/scvs/v5-component-analysis/',
    sources_description: 'OWASP SCVS L1 5.1',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/staticCodeAnalysis'
  },
  {
    title: 'Address compiler and linter warnings before merging',
    description: 'Ensure all compiler and linter warnings are resolved before merging',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'resolveLinterWarnings',
    priority_group: 'P6',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1127.html',
    mitre_description: 'CWE-1127',
    how_to_url: 'https://eslint.org/docs/latest/use/getting-started#installation-and-usage',
    how_to_description: 'ESLint Docs',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#1.warnings_strict',
    sources_description: 'OpenSSF Best Practices Badge Silver Level [warnings_strict]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/resolveLinterWarnings'
  },
  {
    title: 'Use static application security testing for all commits',
    description: 'Ensure all commits are scanned by a static application security testing tool',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'staticAppSecTesting',
    priority_group: 'P6',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1076.html',
    mitre_description: 'CWE-1076',
    how_to_url: 'https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql',
    how_to_description: 'CodeQL Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast',
    sources_description: 'OWASP SCVS L1 6.6OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/staticAppSecTesting'
  },
  {
    title: 'Require commit status checks to pass before merging',
    description: 'Ensure all required commit status checks pass before merging',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'commitStatusChecks',
    priority_group: 'P6',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/358.html',
    mitre_description: 'CWE-358',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/commitStatusChecks'
  },
  {
    title: 'Ensure Security.md meets OpenJS CVD guidelines',
    description: 'Verify that Security.md complies with OpenJS CVD guidelines',
    section_number: '6',
    section_name: 'coordinated vulnerability disclosure',
    code_name: 'securityMdMeetsOpenJSCVD',
    priority_group: 'P7',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/securityMdMeetsOpenJSCVD'
  },
  {
    title: 'Use CVD tools to manage vulnerability reports',
    description: 'Ensure the project utilizes a CVD tool to privately receive and manage external vulnerability reports (e.g., HackerOne, GitHub PVR)',
    section_number: '6',
    section_name: 'coordinated vulnerability disclosure',
    code_name: 'useCVDToolForVulns',
    priority_group: 'P7',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    how_to_url: 'https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-an-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#0.vulnerability_report_private',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [vulnerability_report_private]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/useCVDToolForVulns'
  },
  {
    title: 'Respond to external vulnerability reports in under 14 days',
    description: 'Ensure all external vulnerability reports are addressed within 14 days',
    section_number: '6',
    section_name: 'coordinated vulnerability disclosure',
    code_name: 'vulnResponse14Days',
    priority_group: 'P7',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria#0.vulnerability_report_response',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [vulnerability_report_response]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/vulnResponse14Days'
  },
  {
    title: 'Define clear communication and incident response plans',
    description: 'Establish clear communication and incident response plans',
    section_number: '6',
    section_name: 'coordinated vulnerability disclosure',
    code_name: 'incidentResponsePlan',
    priority_group: 'P7',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/#operations',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/incidentResponsePlan'
  },
  {
    title: 'Assign CVEs to all known security vulnerabilities',
    description: 'Ensure all known security vulnerabilities are issued a CVE',
    section_number: '6',
    section_name: 'coordinated vulnerability disclosure',
    code_name: 'assignCVEForKnownVulns',
    priority_group: 'P7',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#0.release_notes_vulns',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [release_notes_vulns]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/assignCVEForKnownVulns'
  },
  {
    title: 'Include CVE IDs in release notes for security fixes',
    description: 'Ensure release notes include the CVE ID for patched security vulnerabilities',
    section_number: '6',
    section_name: 'coordinated vulnerability disclosure',
    code_name: 'includeCVEInReleaseNotes',
    priority_group: 'P7',
    is_c_scrm: false,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#0.release_notes_vulns',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [release_notes_vulns]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/includeCVEInReleaseNotes'
  },
  {
    title: 'Create regression tests for bugs and security vulnerabilities',
    description: 'Ensure regression tests cover at least 50% of bugs and 100% of security vulnerabilities',
    section_number: '7',
    section_name: 'code quality',
    code_name: 'regressionTestsForVulns',
    priority_group: 'P8',
    is_c_scrm: false,
    level_incubating_status: 'deferrable',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#1.regression_tests_added50',
    sources_description: 'OpenSSF Best Practices Badge Silver Level [regression_tests_added50]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/regressionTestsForVulns'
  },
  {
    title: 'Set default GitHub workflow token permissions to read-only',
    description: 'Ensure GitHub organization default workflow token permissions are set to read-only',
    section_number: '4',
    section_name: 'github workflow permissions',
    code_name: 'defaultTokenPermissionsReadOnly',
    priority_group: 'P9',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/250.html',
    mitre_description: 'CWE-250',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/defaultTokenPermissionsReadOnly'
  },
  {
    title: 'Prevent workflows from creating or approving PRs',
    description: 'Ensure workflows are not allowed to create or approve pull requests',
    section_number: '4',
    section_name: 'github workflow permissions',
    code_name: 'blockWorkflowPRApproval',
    priority_group: 'P9',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/250.html',
    mitre_description: 'CWE-250',
    how_to_url: 'https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#preventing-github-actions-from-creating-or-approving-pull-requests',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/blockWorkflowPRApproval'
  },
  {
    title: 'Disable force push on default branch',
    description: 'Ensure force push is disabled on the default branch',
    section_number: '9',
    section_name: 'source control',
    code_name: 'noForcePushDefaultBranch',
    priority_group: 'P9',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/noForcePushDefaultBranch'
  },
  {
    title: 'Prevent deletion of default branch',
    description: 'Ensure the default branch cannot be deleted',
    section_number: '9',
    section_name: 'source control',
    code_name: 'preventDeletionDefaultBranch',
    priority_group: 'P9',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/267.html',
    mitre_description: 'CWE-267',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/preventDeletionDefaultBranch'
  },
  {
    title: 'Require default branch updates before merging',
    description: 'Ensure the default branch is up to date before allowing merges',
    section_number: '9',
    section_name: 'source control',
    code_name: 'upToDateDefaultBranchBeforeMerge',
    priority_group: 'P9',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/upToDateDefaultBranchBeforeMerge'
  },
  {
    title: 'Restrict GitHub organization secrets to specific repositories',
    description: 'Limit GitHub organization secrets to only be accessible by selected repositories',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'restrictOrgSecrets',
    priority_group: 'P10',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/250.html',
    mitre_description: 'CWE-250',
    how_to_url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#managing-github-actions-permissions-for-your-repository',
    how_to_description: 'Github Docs',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/actions/all_repositories_can_run_github_actions.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/restrictOrgSecrets'
  },
  {
    title: 'Limit GitHub Actions to verified or trusted actions',
    description: 'Ensure GitHub Actions are limited to verified or explicitly trusted actions',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'verifiedActionsOnly',
    priority_group: 'P10',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1357.html',
    mitre_description: 'CWE-1357',
    how_to_url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run',
    how_to_description: 'Github Docs',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/actions/all_github_actions_are_allowed.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/verifiedActionsOnly'
  },
  {
    title: 'Disable self-hosted runners in GitHub organization',
    description: 'Ensure the use of self-hosted runners is disabled in the GitHub organization',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'noSelfHostedRunners',
    priority_group: 'P10',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://capec.mitre.org/data/definitions/439.html',
    mitre_description: 'CAPEC-439',
    how_to_url: 'https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#limiting-the-use-of-self-hosted-runners',
    how_to_description: 'Github Docs',
    sources_url: 'https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners',
    sources_description: 'Github Action Hardening Docs',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/noSelfHostedRunners'
  },
  {
    title: 'Restrict build pipeline code execution to build scripts',
    description: 'Ensure the build pipeline cannot execute arbitrary code outside of a build script',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'noArbitraryCodeInPipeline',
    priority_group: 'P11',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/94.html',
    mitre_description: 'CWE-94',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/noArbitraryCodeInPipeline'
  },
  {
    title: 'Limit workflow write permissions to job level',
    description: 'Ensure workflows are granted write permissions only at the job level',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'limitWorkflowWritePermissions',
    priority_group: 'P11',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    mitre_url: 'https://cwe.mitre.org/data/definitions/250.html',
    mitre_description: 'CWE-250',
    how_to_url: 'https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/limitWorkflowWritePermissions'
  },
  {
    title: 'Avoid script injection from untrusted variables',
    description: 'Ensure script injection is prevented by avoiding untrusted context variables',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'preventScriptInjection',
    priority_group: 'P11',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/454.html',
    mitre_description: 'CWE-454',
    how_to_url: 'https://securitylab.github.com/research/github-actions-untrusted-input/',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/preventScriptInjection'
  },
  {
    title: 'Document consistent and automated build processes',
    description: 'Ensure a consistent and automated build process is documented and followed',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'consistentBuildProcessDocs',
    priority_group: 'P12',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1068.html',
    mitre_description: 'CWE-1068',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/consistentBuildProcessDocs'
  },
  {
    title: 'Support older versions or provide upgrade paths',
    description: 'Ensure commonly used older versions are supported or an upgrade path is documented and provided',
    section_number: '5',
    section_name: 'vulnerability management',
    code_name: 'upgradePathDocs',
    priority_group: 'P12',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#1.maintenance_or_update',
    sources_description: 'OpenSSF Best Practices Badge Silver Level [maintenance_or_update]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/upgradePathDocs'
  },
  {
    title: 'Document software architecture',
    description: 'Ensure the software architecture is clearly documented',
    section_number: '8',
    section_name: 'code review',
    code_name: 'softwareArchitectureDocs',
    priority_group: 'P12',
    is_c_scrm: false,
    level_incubating_status: 'deferrable',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1053.html',
    mitre_description: 'CWE-1053',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#1.documentation_architecture',
    sources_description: 'OpenSSF Best Practices Badge Silver Level [documentation_architecture]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/softwareArchitectureDocs'
  },
  {
    title: 'Automate CI/CD steps in code-based pipelines',
    description: 'Ensure all CI/CD steps are automated through pipelines defined as code',
    section_number: '9',
    section_name: 'source control',
    code_name: 'ciAndCdPipelineAsCode',
    priority_group: 'P12',
    is_c_scrm: true,
    level_incubating_status: 'deferrable',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    how_to_url: 'https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#build-and-related-continuous-integrationcontinuous-delivery-steps-should-all-be-automated-through-a-pipeline-defined-as-code',
    sources_description: 'CNCF SSCP 1.0 #158',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/ciAndCdPipelineAsCode'
  },
  {
    title: 'Pin actions with secrets to full-length commit SHAs',
    description: 'Ensure actions with access to secrets are pinned to a full-length commit SHA',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'pinActionsToSHA',
    priority_group: 'P13',
    is_c_scrm: true,
    level_incubating_status: 'deferrable',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    mitre_url: 'https://cwe.mitre.org/data/definitions/1357.html',
    mitre_description: 'CWE-1357',
    sources_url: 'https://securitylab.github.com/research/github-actions-building-blocks/',
    sources_description: 'Github Docs',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/pinActionsToSHA'
  },
  {
    title: 'Automate monitoring of outdated dependencies',
    description: 'Ensure an automated process is in place to monitor and maintain a list of outdated dependencies',
    section_number: '10',
    section_name: 'dependency inventory',
    code_name: 'automateDependencyManagement',
    priority_group: 'P14',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    how_to_url: 'https://socket.dev/',
    how_to_description: 'Socket.Dev',
    sources_url: 'https://scvs.owasp.org/scvs/v5-component-analysis/',
    sources_description: 'OWASP SCVS L1 5.7',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/automateDependencyManagement'
  },
  {
    title: 'Provide machine-readable dependency lists',
    description: 'Ensure a machine-readable list of all direct and transitive dependencies is available for the software',
    section_number: '10',
    section_name: 'dependency inventory',
    code_name: 'machineReadableDependencies',
    priority_group: 'P14',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    how_to_url: 'https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-the-dependency-graph',
    how_to_description: 'Github Docs',
    sources_url: 'https://scvs.owasp.org/scvs/v1-inventory/#verification-requirements',
    sources_description: 'OWASP SCVS L1 1.3',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/machineReadableDependencies'
  },
  {
    title: 'Uniquely identify modified dependencies',
    description: 'Ensure modified dependencies are uniquely identified and clearly distinguished from the original dependency',
    section_number: '10',
    section_name: 'dependency inventory',
    code_name: 'identifyModifiedDependencies',
    priority_group: 'P14',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'expected',
    sources_url: 'https://scvs.owasp.org/scvs/v6-pedigree-and-provenance/',
    sources_description: 'OWASP SCVS L2 6.5',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/identifyModifiedDependencies'
  },
  {
    title: 'Refresh dependencies with annual releases',
    description: 'Ensure dependencies are refreshed through a new release at least once annually',
    section_number: '5',
    section_name: 'vulnerability management',
    code_name: 'annualDependencyRefresh',
    priority_group: 'P14',
    is_c_scrm: true,
    level_incubating_status: 'expected',
    level_active_status: 'expected',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria?details=true&rationale=true#0.maintained',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [maintained]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/annualDependencyRefresh'
  },
  {
    title: 'Use AAL2/3 passkeys for GitHub access',
    description: 'Ensure GitHub access utilizes a passkey (AAL2) or hardware key (AAL3) activated by a password or biometrics',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'useHwKeyGithubAccess',
    priority_group: 'R1',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    how_to_url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-passkey',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/great-mfa-project/blob/main/security-rationale.md',
    sources_description: 'OpenSSF Great MFA Project Security Rationale',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/useHwKeyGithubAccess'
  },
  {
    title: 'Use AAL2/3 passkeys for non-interactive GitHub access',
    description: 'Ensure non-interactive GitHub access uses a passkey (AAL2) or hardware key (AAL3) activated by a password or biometrics',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'useHwKeyGithubNonInteractive',
    priority_group: 'R1',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    how_to_url: 'https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key-for-a-hardware-security-key',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/great-mfa-project/blob/main/security-rationale.md',
    sources_description: 'OpenSSF Great MFA Project Security Rationale',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/useHwKeyGithubNonInteractive'
  },
  {
    title: 'Use AAL2/3 passkeys in all other contexts',
    description: 'Ensure all other contexts use a passkey (AAL2) or hardware key (AAL3) activated by a password or biometrics',
    section_number: '1',
    section_name: 'user authentication',
    code_name: 'useHwKeyOtherContexts',
    priority_group: 'R1',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://cwe.mitre.org/data/definitions/308.html',
    mitre_description: 'CWE-308',
    sources_url: 'https://github.com/ossf/great-mfa-project/blob/main/security-rationale.md',
    sources_description: 'OpenSSF Great MFA Project Security Rationale',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/useHwKeyOtherContexts'
  },
  {
    title: 'Require approval for forked workflow changes',
    description: 'Ensure changes to workflows from forks require approval for all outside collaborators',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'forkWorkflowApproval',
    priority_group: 'R2',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://capec.mitre.org/data/definitions/180.html',
    mitre_description: 'CAPEC-180',
    sources_url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories',
    sources_description: 'Github Docs',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/forkWorkflowApproval'
  },
  {
    title: 'Use workflow security scanners',
    description: 'Ensure a workflow security scanner is utilized',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'workflowSecurityScanner',
    priority_group: 'R2',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://attack.mitre.org/mitigations/M1047/',
    mitre_description: 'M1047',
    how_to_url: 'https://github.com/step-security/secure-repo',
    how_to_description: 'Step Security secure-repo',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/workflowSecurityScanner'
  },
  {
    title: 'Use GitHub runner security scanners',
    description: 'Ensure a GitHub runner security scanner is utilized',
    section_number: '4',
    section_name: 'github workflows',
    code_name: 'runnerSecurityScanner',
    priority_group: 'R2',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://attack.mitre.org/mitigations/M1047/',
    mitre_description: 'M1047',
    how_to_url: 'https://github.com/step-security/harden-runner',
    how_to_description: 'Step Security harden-runner',
    sources_url: 'https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners',
    sources_description: 'Github Action Hardening Docs',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/runnerSecurityScanner'
  },
  {
    title: 'Require active admins in GitHub organization (activity in 6 months)',
    description: 'Ensure GitHub organization admins have been active within the last 6 months',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'activeAdminsSixMonths',
    priority_group: 'R3',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'n/a',
    mitre_url: 'https://attack.mitre.org/mitigations/M1026/',
    mitre_description: 'M1026',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/member/stale_admin_found.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/activeAdminsSixMonths'
  },
  {
    title: 'Require active members with write access (activity in 6 months)',
    description: 'Ensure GitHub organization members with write permissions have been active within the last 6 months',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'activeWritersSixMonths',
    priority_group: 'R3',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'n/a',
    mitre_url: 'https://attack.mitre.org/mitigations/M1026/',
    mitre_description: 'M1026',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/member/stale_member_found.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/activeWritersSixMonths'
  },
  {
    title: 'Require pull requests before merging',
    description: 'Require pull requests before merging',
    section_number: '9',
    section_name: 'source control',
    code_name: 'PRsBeforeMerge',
    priority_group: 'R4',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://cwe.mitre.org/data/definitions/778.html',
    mitre_description: 'CWE-778',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-pull-request-reviews-before-merging',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/PRsBeforeMerge'
  },
  {
    title: 'Enforce commit sign-off for web based commits',
    description: 'GitHub org requires commit sign-off for web-based commits',
    section_number: '9',
    section_name: 'source control',
    code_name: 'commitSignoffForWeb',
    priority_group: 'R4',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    how_to_url: 'https://docs.github.com/en/organizations/managing-organization-settings/managing-the-commit-signoff-policy-for-your-organization#managing-compulsory-commit-signoffs-for-your-organization',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#require-signed-commits',
    sources_description: 'CNCF SSCP 1.0 #325',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/commitSignoffForWeb'
  },
  {
    title: 'Require signed commits',
    description: 'Require signed commits',
    section_number: '9',
    section_name: 'source control',
    code_name: 'requireSignedCommits',
    priority_group: 'R4',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-signed-commits',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/sscsp.md#require-signed-commits',
    sources_description: 'CNCF SSCP 1.0 #325',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/requireSignedCommits'
  },
  {
    title: 'Include package-lock.json in releases',
    description: 'Commit a package-lock.json file with each release',
    section_number: '10',
    section_name: 'dependency inventory',
    code_name: 'includePackageLock',
    priority_group: 'R5',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    how_to_url: 'https://docs.npmjs.com/cli/v10/commands/npm-sbom',
    how_to_description: 'npm Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#sbom',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/includePackageLock'
  },
  {
    title: 'Require two-party review',
    description: 'Require two party review',
    section_number: '8',
    section_name: 'code review',
    code_name: 'requireTwoPartyReview',
    priority_group: 'R6',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'n/a',
    mitre_url: 'https://capec.mitre.org/data/definitions/670.html',
    mitre_description: 'CAPEC-670',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-pull-request-reviews-before-merging',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#code-review',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/requireTwoPartyReview'
  },
  {
    title: 'Require code owners review',
    description: 'Require code owners review',
    section_number: '8',
    section_name: 'code review',
    code_name: 'requireCodeOwnersReviewForLargeTeams',
    priority_group: 'R6',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'n/a',
    mitre_url: 'https://capec.mitre.org/data/definitions/670.html',
    mitre_description: 'CAPEC-670',
    how_to_url: 'https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#code-review',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/requireCodeOwnersReviewForLargeTeams'
  },
  {
    title: 'Require approved PRs for mainline commits',
    description: 'Require approved PRs for all commits to mainline branches',
    section_number: '9',
    section_name: 'source control',
    code_name: 'requirePRApprovalForMainline',
    priority_group: 'R6',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://capec.mitre.org/data/definitions/670.html',
    mitre_description: 'CAPEC-670',
    how_to_url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches',
    how_to_description: 'Github Docs',
    sources_url: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection',
    sources_description: 'OpenSSF Scorecard',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/requirePRApprovalForMainline'
  },
  {
    title: 'Limit GitHub org owners to fewer than three',
    description: 'Limit the number of GitHub org owners (ideally fewer than three)',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'limitOrgOwners',
    priority_group: 'R7',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://attack.mitre.org/mitigations/M1026/',
    mitre_description: 'M1026',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/member/organization_has_too_many_admins.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/limitOrgOwners'
  },
  {
    title: 'Limit GitHub repo admins to fewer than three',
    description: 'Limit number of GitHub repository admins (ideally fewer than three)',
    section_number: '2',
    section_name: 'user account permissions',
    code_name: 'limitRepoAdmins',
    priority_group: 'R7',
    is_c_scrm: true,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'recommended',
    mitre_url: 'https://capec.mitre.org/data/definitions/180.html',
    mitre_description: 'CAPEC-180',
    sources_url: 'https://best.openssf.org/SCM-BestPractices/github/repository/repository_has_too_many_admins.html',
    sources_description: 'OpenSSF SCM Best Practices',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/limitRepoAdmins'
  },
  {
    title: 'Patch critical/high vulnerabilities in 14 Days',
    description: 'Actively exploited critical and high vulnerabilities patched within 14 Days',
    section_number: '5',
    section_name: 'vulnerability management',
    code_name: 'patchExploitableHighVulns14Days',
    priority_group: 'R8',
    is_c_scrm: false,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria#0.vulnerabilities_critical_fixed',
    sources_description: 'OpenSSF Best Practices Badge Passing Level [vulnerabilities_critical_fixed]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/patchExploitableHighVulns14Days'
  },
  {
    title: 'Patch non-critical vulnerabilities in 60 Days',
    description: 'Non-critical exploitable vulnerabilities patched within 60 Days',
    section_number: '5',
    section_name: 'vulnerability management',
    code_name: 'patchExploitableNoncCriticalVulns60Days',
    priority_group: 'R8',
    is_c_scrm: false,
    level_incubating_status: 'recommended',
    level_active_status: 'recommended',
    level_retiring_status: 'n/a',
    sources_url: 'https://www.bestpractices.dev/en/criteria#0.vulnerabilities_fixed_60_days',
    sources_description: 'OpenSSF Best Practices Badge Silver Level [vulnerabilities_fixed_60_days]',
    implementation_status: 'pending',
    details_url: 'https://openpathfinder.com/docs/checks/patchExploitableNoncCriticalVulns60Days'
  }
]
exports.up = async (knex) => {
  await knex('compliance_checks').insert(list)
}

exports.down = async (knex) => {
  await knex('compliance_checks').del()
}
