services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: visionBoard
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - visionBoard_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  schema-dump:
    image: postgres:17.2
    depends_on:
      - db
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: visionBoard
      POSTGRES_PASSWORD: password
      PGPASSWORD: password  # bypass the password prompt
    volumes:
      - visionBoard_data:/var/lib/postgresql/data
      - ./src/database/schema:/schema
    entrypoint: >
      bash -c "
      pg_dump --host=db --username=visionBoard --schema-only --no-owner --dbname=dashboard > /schema/schema.sql &&
      chmod 644 /schema/schema.sql
      "

volumes:
  visionBoard_data: