name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_DB: dashboard
          POSTGRES_USER: visionBoard
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U visionBoard"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install
      
    - name: Install Playwright system dependencies
      run: npx playwright install-deps
      
    - name: Set up database
      run: |
        npm run db:migrate
        npm run db:seed
      
    - name: Run Playwright tests
      run: |
        # Run the tests with list reporter to avoid hanging on failures
        # Playwright will automatically start and manage the server as configured in playwright.config.js
        npm run test:e2e-ci
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
